version: '3'
services:
    apache:
        build: .docker/apache
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        volumes:
            - .:/app
        depends_on:
            - database
        environment:
            - APP_ENV=dev
            - APP_SECRET=c38170264790969a64d84eea4eeaf46d
            - MONGODB_URL=mongodb://mongo_user:mongo_passwd@database:27017
            - CRON=false
            - XDEBUG=true
        restart: on-failure
    database:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo_user
            - MONGO_INITDB_ROOT_PASSWORD=mongo_passwd
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - .docker/database:/data/db
        restart: on-failure
