version: '3'
services:
    apache:
        build: .docker/apache
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        volumes:
            - .:/app
        depends_on:
            - database
    database:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo_user
            - MONGO_INITDB_ROOT_PASSWORD=mongo_passwd
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - .docker/database:/data/db
