get_status:
    path: /api/status
    controller: App\Core\Infrastructure\Controller\StatusController::getStatus
    methods: ['GET']

user_register:
    path: /register
    controller: App\Core\Infrastructure\Controller\UserAuthorizationController::register
    methods: ['POST']

user_check:
    path: /check
    controller: App\Core\Infrastructure\Controller\UserAuthorizationController::getUserToken
    methods: [ 'GET' ]
